spring.application.name=application
spring.datasource.url=jdbc:postgresql://dpg-d7qgetb7uimc73f51ikg-a.virginia-postgres.render.com:5432/register_products
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
server.port=${PORT:8080}
