spring.application.name=application
spring.datasource.url=jdbc:postgresql://dpg-d7qgetb7uimc73f51ikg-a.virginia-postgres.render.com:5432/register_products
spring.datasource.username=test_dev_pires
spring.datasource.password=ry67U7LzIimKKjlMKNXkaTuteOkLiauf
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
